services:
  mysql:
    image: bankapp/database:1.0.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: bankdb
      MYSQL_USER: bankapp
      MYSQL_PASSWORD: bankpass123
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql_net
      - auth_net
      - bank_net
    deploy:
      replicas: 3

  auth:
    image: bankapp/auth:1.0.0
    environment:
      DB_HOST: mysql
      DB_NAME: bankdb
      DB_USER: bankapp
      DB_PASSWORD: bankpass123
    networks:
      - mysql_net
      - frontend_net
      - bank_net
      - auth_net
    depends_on: [mysql]
    deploy:
      replicas: 3

  bank:
    image: bankapp/bank:1.0.0
    environment:
      DB_HOST: mysql
      DB_NAME: bankdb
      DB_USER: bankapp
      DB_PASSWORD: bankpass123
    networks:
      - mysql_net
      - frontend_net
      - auth_net
      - bank_net
    depends_on: [mysql]
    deploy:
      replicas: 3

  frontend:
    image: bankapp/frontend:1.0.0
    ports:
      - "80:80"
    networks:
      - frontend_net
      - bank_net
      - auth_net
    depends_on: [auth, bank]
    deploy:
      replicas: 3
    

volumes:
  mysql-data:

networks:
  mysql_net:
    driver: overlay
  frontend_net:
    driver: overlay
  auth_net:
    driver: overlay
  bank_net:
    driver: overlay
